language: python

os: linux
dist: bionic

# whitelist
branches:
  only:
    - master
    - dev

git:
    submodules: false

jobs:
  include:
    - name: Python3.8, g++-7
      env:
      - COMPILER=g++-7
      - BUILD_TYPE=Coverage
      - RUN_CTESTS=true
      addons:
        apt:
          packages:
            - g++-7
            - python3.8
            - python3.8-dev
            - libnetcdf-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
      python: 3.8

    - name: Python3.8, g++-8, docs
      env:
      - COMPILER=g++-8
      - BUILD_TYPE=Release
      - RUN_CTESTS=true
      - RELEASE_MAKER=true
      addons:
        apt:
          packages:
            - g++-8
            - python3.8
            - python3.8-dev
            - libnetcdf-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
      python: 3.8

before_install:
    - export CXX=$COMPILER
    - $COMPILER --version
    - python --version

install:
    - python -m pip install pytest numpy

before_script:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --depth=1

script:
    - git clone https://github.com/sizmailov/pyxmopp_tests_dataset.git tests_dataset
    - python setup.py sdist
    - python -m pip install dist/*.tar.gz
    - python -m pytest tests/bindings
    - if $RUN_CTESTS ; then
        mkdir -p _build ;
        (cd _build && cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE) ;
        cmake --build _build --target all -- -j 2 ;
        (cd _build && ctest) ;
      fi ;


after_success:
#    - ( cd docs && bash build.sh ) # patched doxygen is required, disabled for now
    - python -m pip install gcovr
    - if [ "$BUILD_TYPE" == "Coverage" ]; then
        gcovr _build --root=./ --delete --filter='src/.*' --filter='include/.*' --filter='pyxmolpp/.*'  --xml -o coverage.xml ;
        bash <(curl -s https://codecov.io/bash) ;
      fi;
    - if [ "$TRAVIS_BRANCH" == "master" ]  && [ $RELEASE_MAKER ]; then
        DO_GH_PAGES=true;
        DO_PYPI_RELEASE=true;
      fi;
    - if [ "$TRAVIS_BRANCH" == "dev" ]  && [ $RELEASE_MAKER ]; then
          DO_PYPI_PRERELEASE=true;
      fi;

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"


deploy:
  - provider: pages
    verbose: true
    local-dir: docs/_/site/api/python
    cleanup: false
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
      tags: false
      branch: master
      condition: $DO_GH_PAGES

  - provider: pypi
    user: sizmailov
    server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
    password:
      secure: "Nl30LxQNGWXsNTqMBwjHY9CAfDks4reOk0wV89iWjCK+4KjX3dwoa4vB0L+j/a0v8qAHSnwQYfNaFBWnUycwqgViOiDePEp8orM3UCxji/QSVFQ3oQQd6Xxzzpgem/N0pcyhf540xRypAnQyfOZP7vsRnvMyU3s8xRn3Vhws64niZGFtt7MaMfz/dew74ji3+nYrJdZTnuGXXj5oazUArxalVbO7Er3yNYTPEpZ4mo1+6PJEJrPqCyTkYBIRLv5F/JiX37wNv1CF2uKN9QtmB1folC266I5cEAZORvR5TEdP9RQrV32tv0kqt+bLnAFeV0x0zGlVYurgchXyiw3MsW1tPzZlVehjLqKOGxpoPAbZBclsIUfCy5ZG5Dj3qZ/kf2XlP9u+loqYqKMeAVoGNwwYCcZDY98C4RGdvW1AF96JJRLiMtPd3W8bB2lx2MeJRbN1BTDWy0C23NJ9/oluBO3LEBJk6RFZFDlB96viGPr/0Pd05RFPa7bKrdUApShue1AbmyVkDkT263f9Knbdh1VcJVxyoa0Jtg3qIofsdk2hvSKY+UkA3TO8f2Q3WHPIDFQPyLVSL4vNtZ7URdz9HnBKh/sQqWX3ssfOB7hXhCqjmUQ0af9PVUc689Vl2Z2TJKq2RREwDvJJBuQdTEF4ErxNXwwPdN4UG9ys+3Gg7ek="
    distributions: "sdist"
    skip_existing: true
    on:
      branch: dev
      condition: $DO_PYPI_PRERELEASE

  - provider: pypi
    user: sizmailov
    password:
      secure: "cr7uoS3mUnPOCqhwORZ8B+eqMYcejNSZPLpTzE2/oCbmoWgVT6Rb9k+NTFzmWc9KzfLnxYljSOKCXQ92qp1zQvgV7bcqjQjNj8SOdfSndVIGmy3PKLqxuQyo11mecMH2JgPoK8bVHJtxjFjml/jmx6jXTspYlvSFqiDl7t6rXjSKbDpMtePGrmhAnixD1Qw1PodrMzZ4vhcKlpTCn0rb+jmCkAQczRjgvUkB4PUCMB5L1940/LVbLpA7S59nKKgFmPUD6djPk6QqqjK22z2qSFe8EIC0jrN0q1B/U2WGEYHceEByR9PKTwA828i0/RSuslNzVA199VFiDCvPZ/1G1vIysdZ9VdMSpyR/dEZ9AOR2CvdELuf7hGrT4xIck5i1RjjGu2fFQ6p8p8rGJ20czQJp6gMBpVwAVRM6KF9Fv0oH5Xtok9nZXJCzIZ2CpDl/Cu+6+ZK6wIseflJslKvTGY4sJG9sXza54GMBuoQEBHEih3PZ1QLE1ViLnAbQJ04auSqtODuoUkvA/1HY7Z7p48TKJFBT6rAEnihRp755ZtgB7FaKsKK2Kge3BETVdMYw48yrxoZ4RqpEDKcv+8YsoaEOlT2oAJ+8ikpFECl+q9Oc04D4fDRc4Ds33XBdDMwV+rfUMUiFZuvyFo+ACBzo+SOv+izmnTpSNYEvk1UN0+E="
    distributions: "sdist"
    skip_existing: true
    on:
      branch: master
      condition: $DO_PYPI_RELEASE
